using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace PoeExporterGenerator.WikiCommands;

/// <summary>
/// Class used to generate wiki commands.
/// </summary>
[Generator]
internal sealed class WikiCommandsGenerator : IIncrementalGenerator
{
    private const string AttributeName = "AddWikiExporter";
    private const string AttributeFullName = "AddWikiExporterAttribute";
    private const string WikiCommandsClassName = "WikiCommands";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var attributesDataProvider =
            context.SyntaxProvider.CreateSyntaxProvider(ShouldVisit, GetAttributeData);

        var merged = attributesDataProvider.Collect();

        context.RegisterSourceOutput(merged, Output);
    }

    private static bool ShouldVisit(SyntaxNode syntaxNode, CancellationToken cancellationToken)
    {
        if (syntaxNode is not ClassDeclarationSyntax classDeclaration)
        {
            return false;
        }

        var attributes = classDeclaration.AttributeLists;

        if (!HasAttribute(attributes, cancellationToken))
        {
            return false;
        }

        return true;
    }

    private static bool HasAttribute(SyntaxList<AttributeListSyntax> attributeLists, CancellationToken cancellationToken)
    {
        foreach (var attributes in attributeLists)
        {
            cancellationToken.ThrowIfCancellationRequested();
            foreach (var attribute in attributes.Attributes)
            {
                if (attribute.Name is not IdentifierNameSyntax identifierNameSyntax)
                {
                    continue;
                }

                if (identifierNameSyntax.Identifier.ValueText == AttributeName || identifierNameSyntax.Identifier.ValueText == AttributeFullName)
                {
                    return true;
                }
            }
        }

        return false;
    }

    [System.Diagnostics.CodeAnalysis.SuppressMessage(
        "StyleCop.CSharp.NamingRules",
        "SA1313:Parameter names should begin with lower-case letter",
        Justification = "its a record not a method")]
    private readonly record struct AttributeData(IReadOnlyList<string> Exporters, string[] Aliases, string Description, IEnumerable<string> Namespaces);

    private static IReadOnlyList<AttributeData> GetAttributeData(GeneratorSyntaxContext syntaxContext, CancellationToken cancellationToken)
    {
        var symbol = syntaxContext.SemanticModel.GetDeclaredSymbol(syntaxContext.Node);

        var attributes = symbol!.GetAttributes();
        var results = new List<AttributeData>();

        foreach (var attribute in attributes)
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (attribute.AttributeClass?.Name != AttributeName && attribute.AttributeClass?.Name != AttributeFullName)
            {
                continue;
            }

            var types = attribute.ConstructorArguments[0].Values;
            var exporters = new string[types.Length];
            var namespaces = new HashSet<string>();
            for (var i = 0; i < types.Length; i++)
            {
                var type = types[i];
                var casted = (INamedTypeSymbol)type.Value!;

                exporters[i] = casted.Name;
                namespaces.Add(casted.ContainingNamespace.ToString());
            }

            var aliases = Array.ConvertAll(attribute.ConstructorArguments[1].Values.ToArray(), item => (string)item.Value!);
            var description = (string)attribute.ConstructorArguments[2].Value!;

            var attributeData = new AttributeData(exporters, aliases, description, namespaces);
            results.Add(attributeData);
        }

        return results;
    }

    private static void Output(SourceProductionContext sourceProductionContext, ImmutableArray<IReadOnlyList<AttributeData>> attributeDatas)
    {
        if (attributeDatas.Length != 1)
        {
            throw new NotImplementedException($"found more than 1 {nameof(attributeDatas)}");
        }

        var attributes = attributeDatas[0];

        var builder = new StringBuilder("// <auto-generated/>\n\n");

        AddClassUsings(builder, attributes);

        builder.AppendLine($$"""
            using Serilog;
            using System.CommandLine;
            using System.CommandLine.Invocation;

            namespace PoeExporter.WikiExporters;

            internal sealed partial class {{WikiCommandsClassName}}
            {
                private readonly SpecificationWrapper specificationWrapper;
                private readonly ILogger logger;
                private readonly Command command;
                private readonly Option<bool> wiki;
                private readonly Option<bool> print;
                private readonly Option<bool> write;
                private readonly Option<bool> allBut;
            """);

        AddOptionFields(builder, attributes);
        AddConstructor(builder, attributes);
        AddHandler(builder, attributes);

        builder.AppendLine("""
            }
            """);

        var str = builder.ToString();

        sourceProductionContext.AddSource($"{WikiCommandsClassName}.g.cs", str);
    }

    private static void AddClassUsings(StringBuilder builder, IReadOnlyList<AttributeData> attributeDatas)
    {
        var set = new HashSet<string>();

        foreach (var attributeData in attributeDatas)
        {
            foreach (var namespaceName in attributeData.Namespaces)
            {
                set.Add($"using {namespaceName};");
            }
        }

        foreach (var item in set)
        {
            builder.AppendLine(item);
        }
    }

    private static void AddOptionFields(StringBuilder builder, IReadOnlyList<AttributeData> attributeDatas)
    {
        for (var i = 0; i < attributeDatas.Count; i++)
        {
            var data = attributeDatas[i];
            builder.AppendLine($"""

                    /// <summary>Gets option for exporter {string.Join(", ", data.Aliases)}.</summary>
                    private readonly Option<bool> {GetExporterName(i)};
                """);
        }
    }

    private static string GetExporterName(int index)
    {
        return $"exporter{index}";
    }

    private static void AddConstructor(StringBuilder builder, IReadOnlyList<AttributeData> attributeDatas)
    {
        builder.AppendLine($$"""
                
                    /// <summary>
                    /// Initializes a new instance of the <see cref="WikiCommands"/> class.
                    /// </summary>
                    /// <param name="specificationWrapper">specification wrapper.</param>
                    /// <param name="logger">logger.</param>
                    /// <param name="ownerCommand">command to which the method adds subcommands.</param>
                    private {{WikiCommandsClassName}}(SpecificationWrapper specificationWrapper, ILogger logger, Command ownerCommand)
                    {
                        this.specificationWrapper = specificationWrapper;
                        this.logger = logger;

                        command = new Command("wiki", "exports wiki data");
                        ownerCommand.Add(command);

                        wiki = new Option<bool>(new string[] { "-w", "--wiki" }, "Write to the poewiki page");
                        command.Add(wiki);

                        print = new Option<bool>(new string[] { "-p", "--print" }, "Print the contents of the file");
                        command.Add(print);

                        write = new Option<bool>(new string[] { "-wr", "--write" }, "Write to file");
                        command.Add(write);

                        allBut = new Option<bool>(new string[] { "--allbut" }, "Exports the data of all wiki exporters but the ones specified");
                        command.Add(allBut);
                """);

        for (var i = 0; i < attributeDatas.Count; i++)
        {
            var data = attributeDatas[i];
            var preparedAliases = PrepareAliases(data.Aliases);
            var exporterName = GetExporterName(i);
            builder.AppendLine($$"""

                        {{exporterName}} = new Option<bool>(new string[] { {{string.Join(", ", preparedAliases)}} }, "{{data.Description}}");
                        command.Add({{exporterName}});
                """);
        }

        builder.AppendLine("""
            
                    command.SetHandler(Handler);
                }
            """);
    }

    private static string[] PrepareAliases(IReadOnlyList<string> aliases)
    {
        var preparedAliases = new string[aliases.Count];
        for (var aliasCounter = 0; aliasCounter < aliases.Count; aliasCounter++)
        {
            var alias = aliases[aliasCounter];
            preparedAliases[aliasCounter] = $"\"{alias}\"";
        }

        return preparedAliases;
    }

    private static void AddHandler(StringBuilder builder, IReadOnlyList<AttributeData> attributeDatas)
    {
        builder.AppendLine($$"""

                private void Handler(InvocationContext context)
                {
            """);

        for (var i = 0; i < attributeDatas.Count; i++)
        {
            var exporterName = GetExporterName(i);
            var methodName = GetExporterHandlerName(exporterName);
            builder.AppendLine($"""
                        {methodName}(context);
                """);
        }

        builder.AppendLine("""
                }
            """);

        for (var i = 0; i < attributeDatas.Count; i++)
        {
            var attribute = attributeDatas[i];
            var exporterName = GetExporterName(i);
            AddExporterHandler(builder, attribute, exporterName);
        }
    }

    private static string GetExporterHandlerName(string exporterName)
    {
        var methodName = $"Handle{exporterName}";

        return methodName;
    }

    private static void AddExporterHandler(StringBuilder builder, AttributeData attribute, string exporterName)
    {
        var methodName = GetExporterHandlerName(exporterName);
        builder.AppendLine($$"""

                    /// <summary>
                    /// handler for <see cref="{{exporterName}}"/> - {{string.Join(", ", attribute.Aliases)}}.
                    /// </summary>
                    private void {{methodName}}(InvocationContext context)
                    {
                        var allButResult = context.ParseResult.GetValueForOption(allBut);
                        var exporterResult = context.ParseResult.GetValueForOption({{exporterName}});
                        var wikiResult = context.ParseResult.GetValueForOption(wiki);
                        var printResult = context.ParseResult.GetValueForOption(print);
                        var writeResult = context.ParseResult.GetValueForOption(write);

                        if (allButResult && exporterResult)
                        {
                            return;
                        }

                        if (!allButResult && !exporterResult)
                        {
                            return;
                        }
                """);

        AddIndividualExporters(builder, attribute.Exporters);

        AddWikiExporting(builder, attribute.Exporters);

        AddPrintExporting(builder, attribute.Exporters);

        AdWriteExporting(builder, attribute.Exporters);

        builder.AppendLine("""
                }
            """);
    }

    private static void AddIndividualExporters(StringBuilder builder, IReadOnlyList<string> exporters)
    {
        for (var i = 0; i < exporters.Count; i++)
        {
            var exporter = exporters[i];
            var instance = GetExporterInstanceName(i);
            var result = GetExporterResultName(i);
            builder.AppendLine($"""

                        IExporter<{exporter}> {instance} = {exporter}.Create(specificationWrapper, logger);
                        var {result} = {instance}.Export();
                """);
        }
    }

    private static string GetExporterInstanceName(int index)
    {
        return $"exporterInstance{index}";
    }

    private static string GetExporterResultName(int index)
    {
        return $"result{index}";
    }

    private static void AddWikiExporting(StringBuilder builder, IReadOnlyList<string> exporters)
    {
        builder.AppendLine($$"""

                    if (wikiResult)
                    {
                        // export to wiki here. TODO
                    }
            """);
    }

    private static void AddPrintExporting(StringBuilder builder, IReadOnlyList<string> exporters)
    {
        builder.AppendLine($$"""

                    if (printResult)
                    {
            """);

        for (var i = 0; i < exporters.Count; i++)
        {
            var resultName = GetExporterResultName(i);
            builder.AppendLine($"""
                        logger.Information({resultName});
            """);
        }

        builder.AppendLine("""
                    }
            """);
    }

    private static void AdWriteExporting(StringBuilder builder, IReadOnlyList<string> exporters)
    {
        builder.AppendLine($$"""

                    if (writeResult)
                    {
                        // export to file here. TODO
                    }
            """);
    }
}
