// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Property names are autogenerated from a file.", Scope = "namespaceanddescendants", Target = "~N:PoeData.Specifications.DatFiles")]
[assembly: SuppressMessage("Design", "CA1056:URI-like properties should not be strings", Justification = "Property names are autogenerated from a file.", Scope = "namespaceanddescendants", Target = "~N:PoeData.Specifications.DatFiles")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "Property names are autogenerated from a file.", Scope = "namespaceanddescendants", Target = "~N:PoeData.Specifications.DatFiles")]