using PoeDataGenerator.RepositoryGenerators;
using PoeDataGenerator.SchemaJson;
using System.Text;

namespace PoeDataGenerator.Specification;

/// <summary>
/// Class containing code for generating Specification.cs file.
/// </summary>
internal class SpecificationFileGenerator
{
    private readonly IReadOnlyList<Table> schemaTables;

    /// <summary>Gets generated code.</summary>
    public string Code { get; }

    /// <summary>Gets file name.</summary>
    public string FileName { get; } = "Specification.g.cs";

    /// <summary>
    /// Initializes a new instance of the <see cref="SpecificationFileGenerator"/> class.
    /// </summary>
    /// <param name="logger">logger.</param>
    /// <param name="schemaTables">schema tables.</param>
    public SpecificationFileGenerator(IReadOnlyList<Table> schemaTables)
    {
        this.schemaTables = schemaTables;
        Code = Generate();
    }

    private string Generate()
    {
        var builder = new StringBuilder();

        builder.AppendLine($$"""
            // <auto-generated/>
            // this file is auto generated
            // the generated class is partial, please extend it in another file
            #nullable enable
            
            using PoeData.Specifications.Repositories;
            using Serilog;
            
            namespace PoeData.Specifications;
            
            /// <summary>
            /// Class containing all Path of Exile data.
            /// </summary>
            public sealed partial class Specification
            {
            """);

        AppendFields(builder);
        AppendLoadMethods(builder);

        builder.AppendLine("""
            }
            """);

        var str = builder.ToString();

        return str;
    }

    private void AppendFields(StringBuilder builder)
    {
        foreach (var table in schemaTables)
        {
            var className = RepositoryGenerator.GenerateRepositoryClassName(table.Name);
            var fieldName = GenerateFieldName(className);
            builder.AppendLine($"""
                    private {className}? {fieldName};
                """);
        }
    }

    private void AppendLoadMethods(StringBuilder builder)
    {
        foreach (var table in schemaTables)
        {
            var className = RepositoryGenerator.GenerateRepositoryClassName(table.Name);
            var fieldName = GenerateFieldName(className);
            builder.AppendLine($$"""

                    /// <summary>
                    /// Gets {{className}} data.
                    /// </summary>
                    /// <returns>repository of {{className}}.</returns>
                    public {{className}} {{GenerateLoadRepositoryMethodName(className)}}()
                    {
                        {{fieldName}} ??= new {{className}}(logger, this);
                        return {{fieldName}};
                    }
                """);
        }
    }

    /// <summary>
    /// Generated name of the method to Load repository.
    /// </summary>
    /// <param name="repositoryClassName">repository class name.</param>
    /// <returns>method name.</returns>
    internal static string GenerateLoadRepositoryMethodName(string repositoryClassName)
    {
        return $"Load{repositoryClassName}";
    }

    private static string GenerateFieldName(string className)
    {
        return className.ToLower();
    }
}
