using PoeDataGenerator.GeneratorHelpers;
using PoeDataGenerator.ParsedColumns;
using PoeDataGenerator.ParsedColumns.Helpers;
using PoeDataGenerator.RepositoryGenerators;
using PoeDataGenerator.Specification;
using System.Text;

namespace PoeDataGenerator.DatFiles;

/// <summary>
/// Class containing parsed table data.
/// </summary>
internal sealed class DatFileGenerator
{
    private readonly ParsedSchemaTable parsedTable;

    /// <summary>Gets string with class name.</summary>
    internal string ClassName { get; }

    /// <summary>Gets generated code.</summary>
    public string Code { get; }

    /// <summary>Gets file name.</summary>
    public string FileName { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="DatFileGenerator"/> class.
    /// </summary>
    /// <param name="logger">logger.</param>
    /// <param name="parsedTable">Table to parse.</param>
    public DatFileGenerator(ParsedSchemaTable parsedTable)
    {
        this.parsedTable = parsedTable;

        ClassName = GenerateClassName(parsedTable.Name);

        FileName = GenerateFileName(ClassName);

        Code = Generate();
    }

    /// <summary>
    /// Generates the class name for the table.
    /// </summary>
    /// <param name="tableName">Table name to generate the class name for.</param>
    /// <returns>class name string.</returns>
    internal static string GenerateClassName(string tableName)
    {
        return $"{tableName}Dat";
    }

    /// <summary>
    /// Generates the file name based on the class name.
    /// </summary>
    /// <param name="className">class name for which the method generates the file name for.</param>
    /// <returns>file name string.</returns>
    private static string GenerateFileName(string className)
    {
        return $"{className}.g.cs";
    }

    private string Generate()
    {
        var builder = new StringBuilder();

        var datFileName = $"{parsedTable.Name}.dat";

        builder.AppendLine($$"""
                // <auto-generated/>
                // this file is auto generated
                // the generated class is partial, please extend it in another file
                #nullable enable

                using System.Collections.ObjectModel;
                using PoeData.Specifications.Repositories;

                namespace PoeData.Specifications.DatFiles;

                /// <summary>
                /// Class containing {{datFileName}} data.
                /// </summary>
                public sealed partial class {{ClassName}}
                {
                """);

        AppendProperties(builder, parsedTable.ParsedColumns);

        AppendConstructor(builder);

        AppendGetReferencedItems(builder);

        builder.AppendLine("}"); // class end bracket

        var str = builder.ToString();

        return str;
    }

    private static void AppendProperties(StringBuilder builder, IReadOnlyList<IParsedColumn> parsedColumns)
    {
        for (var i = 0; i < parsedColumns.Count; i++)
        {
            var column = parsedColumns[i];
            var lines = column.GetPropertyStrings();

            foreach (var line in lines)
            {
                if (string.IsNullOrEmpty(line))
                {
                    continue;
                }

                builder.AppendLine($"{Tabs.Tab1}{line}");
            }

            if (i < parsedColumns.Count - 1)
            {
                builder.AppendLine();
            }
        }
    }

    private void AppendConstructor(StringBuilder builder)
    {
        builder.AppendLine($$"""

                private readonly Specification specification;

                public {{ClassName}}(Specification specification)
                {
                    this.specification = specification;
                }
            """);
    }

    private void AppendGetReferencedItems(StringBuilder builder)
    {
        foreach (var column in parsedTable.ParsedColumns)
        {
            // hackfix for enum rows
            if (column is EnumRowArrayColumn || column is EnumRowNonArrayColumn)
            {
                continue;
            }

            if (column.ReferencedTable is null)
            {
                continue;
            }

            if (column.ReferencedColumn is null)
            {
                AppendGetReferencedItemsByIndex(builder, column);
            }
            else
            {
                AppendGetReferencedItemsByMethod(builder, column);
            }
        }
    }

    private static string GenerateGetReferencedItemMethodName(string propertyName)
    {
        return $"GetItemFor{propertyName}";
    }

    private static string GenerateGetReferencedItemsMethodName(string propertyName)
    {
        return $"GetItemsFor{propertyName}";
    }

    private void AppendGetReferencedItemsByIndex(StringBuilder builder, IParsedColumn column)
    {
        if (column.ReferencedTable is null)
        {
            return;
        }

        var repositoryName = RepositoryGenerator.GenerateRepositoryClassName(column.ReferencedTable);
        var loadRepositoryMethod = SpecificationFileGenerator.GenerateLoadRepositoryMethodName(repositoryName);
        var returnedItem = GenerateClassName(column.ReferencedTable);

        if (!column.Type.IsList)
        {
            var methodName = GenerateGetReferencedItemMethodName(column.ClassPropertyName);

            builder.AppendLine($$"""

                    public {{returnedItem}}? {{methodName}}()
                    {
                        if ({{column.ClassPropertyName}} is null)
                        {
                            return null;
                        }

                        return specification.{{loadRepositoryMethod}}().Items[{{column.ClassPropertyName}}.Value];
                    }
                """);
        }
        else
        {
            var methodName = GenerateGetReferencedItemsMethodName(column.ClassPropertyName);

            var keyType = column.Type.InnerTypes[0].NonNullableType;
            builder.AppendLine($$"""

                    public IReadOnlyList<ResultItem<{{keyType}}, {{returnedItem}}>> {{methodName}}()
                    {
                        var items = new List<ResultItem<{{keyType}}, {{returnedItem}}>>();

                        var repository = specification.{{loadRepositoryMethod}}();
                        foreach (var key in {{column.ClassPropertyName}})
                        {
                            var item = repository.Items[key];
                            var parsed = new ResultItem<{{keyType}}, {{returnedItem}}>(key, item);
                            items.Add(parsed);
                        }

                        return items;
                    }
                """);
        }
    }

    private void AppendGetReferencedItemsByMethod(StringBuilder builder, IParsedColumn column)
    {
        if (column.ReferencedTable is null || column.ReferencedColumn is null)
        {
            return;
        }

        var repositoryName = RepositoryGenerator.GenerateRepositoryClassName(column.ReferencedTable);
        var getReferencedMethodName = RepositoryGetMethodsHelper.GenerateGetByMethodName(column.ReferencedColumn);
        var loadRepositoryMethod = SpecificationFileGenerator.GenerateLoadRepositoryMethodName(repositoryName);
        var returnedItem = GenerateClassName(column.ReferencedTable);

        if (!column.Type.IsList)
        {
            var methodName = GenerateGetReferencedItemMethodName(column.ClassPropertyName);

            builder.AppendLine($$"""

                    public {{returnedItem}}? {{methodName}}()
                    {
                        return specification.{{loadRepositoryMethod}}().{{getReferencedMethodName}}({{column.ClassPropertyName}});
                    }
                """);
        }
        else
        {
            var methodName = GenerateGetReferencedItemsMethodName(column.ClassPropertyName);

            var keyType = column.Type.InnerTypes[0].NonNullableType;
            builder.AppendLine($$"""

                    public IReadOnlyList<ResultItem<{{keyType}}, {{returnedItem}}>> {{methodName}}()
                    {
                        var items = new List<ResultItem<{{keyType}}, {{returnedItem}}>>();

                        var repository = specification.{{loadRepositoryMethod}}();
                        foreach (var key in {{column.ClassPropertyName}})
                        {
                            var item = repository.{{getReferencedMethodName}}(key);

                            if (item is null)
                            {
                                throw new NotImplementedException("reference to a null");
                            }

                            var parsed = new ResultItem<{{keyType}}, {{returnedItem}}>(key, item);
                            items.Add(parsed);
                        }

                        return items;
                    }
                """);
        }
    }
}
