using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using PoeExporterGenerator.LuaGenerator;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PoeExporterGenerator;

/// <summary>
/// Class containing code for <see cref="DatJsonExporter"/>.
/// </summary>
[Generator]
internal sealed class DatJsonExporterGenerator : ISourceGenerator
{
    private const string DatJsonExporter = nameof(DatJsonExporter);
    private const string Specification = nameof(Specification);
    private const string SpecificationVarName = "specification";
    private const string LoggerVarName = "logger";
    private const string ExceptionCounterVarName = "exceptionCounter";
    private const string ThrowOnExceptionVarName = "throwOnException";

    /// <inheritdoc/>
    public void Execute(GeneratorExecutionContext context)
    {
        var classDeclarations = context.Compilation.SyntaxTrees
            .SelectMany(syntaxTree => syntaxTree.GetRoot().DescendantNodes())
            .OfType<ClassDeclarationSyntax>()
            .ToArray();

        var datJsonExporterDeclaration = classDeclarations
            .Where(x => x.Identifier.ValueText == DatJsonExporter).First();
        var datJsonExporterNamespace = LuaStringHelpers.GetNamespace(datJsonExporterDeclaration);

        var builder = new StringBuilder();
        builder.AppendLine($$"""
            // <auto-generated/>
            using System;

            namespace {{datJsonExporterNamespace}};

            internal sealed partial class {{DatJsonExporter}}
            {
            """);

        var methods = AddLoadMethods(context, builder);
        AddRunAllMethod(methods, builder);

        builder.AppendLine("}"); // class end bracket

        var source = builder.ToString();

        // Add the source code to the compilation
        context.AddSource($"{DatJsonExporter}.g.cs", source);
    }

    /// <inheritdoc/>
    public void Initialize(GeneratorInitializationContext context)
    {
    }

    // https://stackoverflow.com/a/68733955
    private static IEnumerable<ITypeSymbol> GetAllTypes(INamespaceSymbol root)
    {
        foreach (var namespaceOrTypeSymbol in root.GetMembers())
        {
            if (namespaceOrTypeSymbol is INamespaceSymbol @namespace)
            {
                foreach (var nested in GetAllTypes(@namespace))
                {
                    yield return nested;
                }
            }
            else if (namespaceOrTypeSymbol is ITypeSymbol type)
            {
                yield return type;
            }
        }
    }

    private static string[] AddLoadMethods(GeneratorExecutionContext context, StringBuilder builder)
    {
        var specification = GetSpecification(context);
        var members = specification.GetMembers();

        var result = new List<string>();

        foreach (var member in members)
        {
            if (!member.Name.StartsWith("Load"))
            {
                continue;
            }

            AddLoadMethod(builder, member);
            result.Add(member.Name);
        }

        return result.ToArray();
    }

    private static ITypeSymbol GetSpecification(GeneratorExecutionContext context)
    {
        var poeData = context.Compilation.GlobalNamespace.GetNamespaceMembers()
            .Where(x => x.Name == "PoeData").First();

        var types = context.Compilation.SourceModule.ReferencedAssemblySymbols.SelectMany(a =>
        {
            try
            {
                var main = a.Identity.Name
                .Split('.')
                .Aggregate(a.GlobalNamespace, (s, c) => s.GetNamespaceMembers().Single(m => m.Name.Equals(c)));

                return GetAllTypes(main);
            }
            catch
            {
                return Enumerable.Empty<ITypeSymbol>();
            }
        });

        var specification = types.Where(x => x.Name == Specification).First();

        return specification;
    }

    private static void AddLoadMethod(StringBuilder builder, ISymbol member)
    {
        builder.AppendLine($$"""

                private void {{member.Name}}()
                {
                    try
                    {
                        var res = {{SpecificationVarName}}.{{member.Name}}();
                        Save(res, "{{member.Name}}");
                    }
                    catch (Exception e)
                    {
                        {{LoggerVarName}}.Error("failed to load {name}\n{error}", "{{member.Name}}", e);
                        {{ExceptionCounterVarName}}++;
                        
                        if ({{ThrowOnExceptionVarName}})
                        {
                            throw e;
                        }
                    }
                }
            """);
    }

    private void AddRunAllMethod(string[] methods, StringBuilder builder)
    {
        builder.AppendLine($$"""

                private partial void RunAll()
                {
                    // {{LoggerVarName}}.Debug("running code generated code");
            """);

        foreach (var method in methods)
        {
            builder.AppendLine($"""
                        {method}();
                """);
        }

        builder.AppendLine("""
                }
            """);
    }
}
