using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PoeExporterGenerator;

/// <summary>
/// Class used to generate to lua strings methods.
/// </summary>
[Generator]
internal sealed class ToLuaStringsGenerator : ISourceGenerator
{
    private const string InterfaceName = "ILuaExporter";
    private const string MethodNameToImplement = "ToLuaStrings";
    private const string AttributeName = "LuaPropertyName";

    /// <inheritdoc/>
    public void Execute(GeneratorExecutionContext context)
    {
        var classDeclarations = context.Compilation.SyntaxTrees
            .SelectMany(syntaxTree => syntaxTree.GetRoot().DescendantNodes())
            .OfType<ClassDeclarationSyntax>();
        var classes = new HashSet<ClassDeclarationSyntax>();
        foreach (var classDeclaration in classDeclarations)
        {
            if (classDeclaration.BaseList is null)
            {
                continue;
            }

            var test = classDeclaration.BaseList.Types;
            foreach (var item in classDeclaration.BaseList.Types)
            {
                if (item.Type is GenericNameSyntax { Identifier.ValueText: InterfaceName })
                {
                    classes.Add(classDeclaration);
                    break;
                }
            }
        }

        foreach (var classDeclaration in classes)
        {
            ImplementMethod(context, classDeclaration);
        }

    }

    /// <inheritdoc/>
    public void Initialize(GeneratorInitializationContext context)
    {
    }

    private void ImplementMethod(GeneratorExecutionContext context, ClassDeclarationSyntax classDeclaration)
    {
        var builder = new StringBuilder();
        var className = classDeclaration.Identifier.ValueText;
        var namespaceDeclaration =
            classDeclaration.Parent as BaseNamespaceDeclarationSyntax ?? throw new NamespaceNotFoundException();
        var classNamespace = namespaceDeclaration.Name;
        var modifiers = classDeclaration.Modifiers;

        builder.AppendLine($$"""
            // <auto-generated/>

            using PoeExporter.WikiExporters.Lua.Helpers;
            
            namespace {{classNamespace}};

            {{classDeclaration.Modifiers}} class {{className}}
            {
                public partial LuaString[] {{MethodNameToImplement}}(int currentIndentation)
                {
                    var strings = new List<LuaString>();

                    var bracket = new LuaString("{", currentIndentation);
                    strings.Add(bracket);
                    currentIndentation++;

            """);

        foreach (var member in classDeclaration.Members)
        {
            if (member is not PropertyDeclarationSyntax property)
            {
                continue;
            }

            var luaPropertyName = GetLuaPropertyName(property);
            var actualPropertyName = property.Identifier.ValueText;
            var variableName = $"{actualPropertyName.ToLower()}LuaStrings";

            builder.AppendLine($"""
                        var {variableName} = LuaString.Generate("{luaPropertyName}", {actualPropertyName}, currentIndentation);
                        strings.AddRange({variableName});

                """);
        }

        builder.AppendLine("""
                    currentIndentation--;
                    var endBracket = new LuaString("}", currentIndentation);
                    strings.Add(endBracket);

                    return strings.ToArray();
                }
            }
            """);

        var str = builder.ToString();

        context.AddSource($"{className}.g.cs", str);
    }

    private static string GetLuaPropertyName(PropertyDeclarationSyntax property)
    {
        var attributesList = property.AttributeLists;
        foreach (var attributes in attributesList)
        {
            foreach (var attribute in attributes.Attributes)
            {
                if (attribute.Name is not IdentifierNameSyntax name || name.Identifier.ValueText != AttributeName)
                {
                    continue;
                }

                if (attribute.ArgumentList is null)
                {
                    continue;
                }

                var overridenNameSyntax = attribute.ArgumentList.Arguments[0];

                if (overridenNameSyntax.Expression is not LiteralExpressionSyntax expression)
                {
                    continue;
                }

                var overridenName = expression.Token.ValueText;

                return overridenName;
            }
        }

        // if the property name is not overriden with the attribute default to actual property name
        return property.Identifier.ValueText;
    }
}
