namespace PoeExporter.WikiExporters.Lua.Helpers;

/// <summary>
/// Interface with lua exporter methods.
/// </summary>
/// <typeparam name="T">type of the exporter.</typeparam>
internal interface ILuaExporter<T>
{
    /// <summary>
    /// Converts the object to lua strings.
    /// </summary>
    /// <param name="currentIndentation">current indentation.</param>
    /// <returns>converted object in lua strings.</returns>
    /// <remarks>This method is not meant to be declared manually as as it's generated by a source generator.</remarks>
    internal LuaString[] ToLuaStrings(int currentIndentation = 0);
}
