namespace PoeExporter.WikiExporters.Lua.Helpers;

/// <summary>
/// Interface used to specify which classes need lua exporter methods generated by generator.
/// </summary>
/// <typeparam name="T">type of the exporter.</typeparam>
internal interface ILuaExporter<T>
{
}