namespace PoeExporter.WikiExporters.Lua.Helpers;

/// <summary>
/// Attribute used to mark lua items which need their lua methods generated by the source generator.
/// </summary>
[AttributeUsage(AttributeTargets.Class)]
internal sealed class LuaItemAttribute : Attribute
{
}
