using Serilog;
using SpecificationGenerator.ColumnGenerators;
using System.Diagnostics;
using System.Text;

namespace SpecificationGenerator;

/// <summary>
/// Class containing parsed table data.
/// </summary>
internal sealed class DatFileGenerator
{
    private readonly ParsedSchemaTable parsedTable;
    private readonly ILogger logger;

    /// <summary>Gets string with class name.</summary>
    internal string ClassName { get; }

    /// <summary>Gets generated code.</summary>
    public string Code { get; }

    /// <summary>Gets file name.</summary>
    public string FileName { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="DatFileGenerator"/> class.
    /// </summary>
    /// <param name="logger">logger.</param>
    /// <param name="parsedTable">Table to parse.</param>
    public DatFileGenerator(ILogger logger, ParsedSchemaTable parsedTable)
    {
        this.logger = logger;
        this.parsedTable = parsedTable;

        ClassName = GenerateClassName(parsedTable.Name);

        FileName = GenerateFileName(ClassName);

        Code = Generate();
    }

    /// <summary>
    /// Generates the class name for the table.
    /// </summary>
    /// <param name="tableName">Table name to generate the class name for.</param>
    /// <returns>class name string.</returns>
    internal static string GenerateClassName(string tableName)
    {
        return $"{tableName}Dat";
    }

    /// <summary>
    /// Generates the file name based on the class name.
    /// </summary>
    /// <param name="className">class name for which the method generates the file name for.</param>
    /// <returns>file name string.</returns>
    private static string GenerateFileName(string className)
    {
        return $"{className}.cs";
    }

    private string Generate()
    {
        var startTimestamp = Stopwatch.GetTimestamp();

        var builder = new StringBuilder();

        var datFileName = $"{parsedTable.Name}.dat";

        // builder.AppendLine("// <auto-generated />");
        builder.AppendLine($$"""
                // this file is auto generated
                // the generated class is partial, please extend it in another file
                #nullable enable

                using PoeData.Extensions;
                using System.Collections.ObjectModel;
                using System.Text;

                namespace PoeData.Specifications.DatFiles;

                /// <summary>
                /// Class containing {{datFileName}} data.
                /// </summary>
                public sealed partial class {{ClassName}}
                {
                """);

        AppendProperties(builder, parsedTable.ParsedColumns);

        builder.AppendLine("}"); // class end bracket

        var str = builder.ToString();

        logger.Verbose("generated {fileName} string in {elapsed}", FileName, Stopwatch.GetElapsedTime(startTimestamp));

        return str;
    }

    private static void AppendProperties(StringBuilder builder, IReadOnlyList<IParsedColumn> parsedColumns)
    {
        for (var i = 0; i < parsedColumns.Count; i++)
        {
            var column = parsedColumns[i];
            var lines = column.GetPropertyStrings();

            foreach (var line in lines)
            {
                if (string.IsNullOrEmpty(line))
                {
                    continue;
                }

                builder.AppendLine($"{Tabs.Tab1}{line}");
            }

            if (i < parsedColumns.Count - 1)
            {
                builder.AppendLine();
            }
        }
    }
}
