using Serilog;
using SpecificationGenerator.SchemaJson;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;

namespace SpecificationGenerator;

/// <summary>
/// Class containing parsed table data.
/// </summary>
internal class ParsedTable
{
    private readonly Table table;
    private readonly ILogger logger;
    private readonly StringBuilder builder;
    private readonly ColumnTypeData[] parsedColumnTypeData;
    private readonly string[] columnNames;
    private readonly string className;

    /// <summary>
    /// Initializes a new instance of the <see cref="ParsedTable"/> class.
    /// </summary>
    /// <param name="table">Table to parse.</param>
    /// <param name="logger">logger.</param>
    public ParsedTable(Table table, ILogger logger)
    {
        this.table = table;
        this.logger = logger;

        // parsing is done here
        builder = new StringBuilder();

        className = TableNameToClassName(table.Name);
        var datFileName = $"{table.Name}.dat";

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// this file is auto generated");
        builder.AppendLine("// the generated class is partial, please extend it in another file\n");

        builder.AppendLine("using PoeData.Extensions;");
        builder.AppendLine("using System.Collections.ObjectModel;");
        builder.AppendLine("using System.Text;");
        builder.AppendLine();
        builder.AppendLine($$"""
                namespace PoeData.Specifications.SpecificationFiles;

                /// <summary>
                /// Class containing {{datFileName}} data.
                /// </summary>
                public sealed partial class {{className}} : ISpecificationFile<{{className}}>
                {
                """);

        (parsedColumnTypeData, columnNames) = AppendProperties();

        AppendLoadMethod();

        builder.AppendLine("}");

        var str = builder.ToString();
        logger.Debug("AbyssObjects");
    }

    private (ColumnTypeData[] parsedColumns, string[] columnNames) AppendProperties()
    {
        var unknownCounter = 0;
        var columnNames = new string[table.Columns.Length];
        var parsedColumns = new ColumnTypeData[table.Columns.Length];

        for (var i = 0; i < table.Columns.Length; i++)
        {
            var column = table.Columns[i];
            (var columnName, unknownCounter, var isUnknown) = GetColumnName(column, unknownCounter);
            var columnTypeData = GetColumnTypeData(column, isUnknown);
            columnNames[i] = columnName;
            parsedColumns[i] = columnTypeData;

            if (column.Type == "bool")
            {
                builder.AppendLine($"    /// <summary> Gets a value indicating whether {columnName} is set.</summary>");
            }
            else
            {
                builder.AppendLine($"    /// <summary> Gets {columnName}.</summary>");
            }

            builder.AppendLine($$"""
                        public required {{columnTypeData.Value}} {{columnName}} { get; init; }
                    """);

            builder.AppendLine();
        }

        return (parsedColumns, columnNames);
    }

    private static string TableNameToClassName(string tableName)
    {
        return tableName;

        // doesnt work with stuff like MonsterVarieties
        // var className = tableName[..^1];
        // return className;
    }

    private static ColumnTypeData GetColumnTypeData(Column column, bool isUnknown)
    {
        var result = string.Empty;
        var isArray = column.Array;
        var isForeignRow = false;
        var columnTypeString = column.Type;
        var baseColumnType = string.Empty;
        var columnType = ColumnTypes.None;

        if (isArray && isUnknown)
        {
            throw new NotImplementedException($"{nameof(isArray)} && {nameof(isUnknown)} == true"); // array of unknowns or unknown of arrays?
        }

        if (columnTypeString == "foreignrow")
        {
            var className = TableNameToClassName(column.References.Table);
            isForeignRow = true;
            columnType = ColumnTypes.ForeignRow;

            // non arrays need to be nullable
            // arrays will just have length 0 if necessary
            if (isArray)
            {
                baseColumnType = className;
            }
            else
            {
                baseColumnType = $"{className}?";
            }
        }
        else if (columnTypeString == "bool")
        {
            baseColumnType = "bool";
            columnType = ColumnTypes.Bool;
        }
        else if (columnTypeString == "i32")
        {
            baseColumnType = "int";
            columnType = ColumnTypes.Int;
        }
        else if (columnTypeString == "string")
        {
            baseColumnType = "string";
            columnType = ColumnTypes.String;
        }
        else if (columnTypeString == "row")
        {
            var className = TableNameToClassName(column.Name);
            baseColumnType = $"{className}?"; // references another row in the same class
            columnType = ColumnTypes.Row;
        }
        else if (columnTypeString == "f32")
        {
            baseColumnType = "float";
            columnType = ColumnTypes.Float;
        }
        else if (columnTypeString == "array")
        {
            baseColumnType = "null";
            columnType = ColumnTypes.None;
        }
        else if (columnTypeString == "enumrow")
        {
            var className = TableNameToClassName(column.References.Table);

            // can enumrow be null?
            // baseColumnType = $"{className}?";
            baseColumnType = className;

            isForeignRow = true;
            columnType = ColumnTypes.Enumrow;
        }
        else
        {
            throw new NotImplementedException($"unknown {nameof(columnTypeString)} == {columnTypeString}");
        }

        var actualColumnType = string.Empty;
        if (isArray)
        {
            actualColumnType = $"ReadOnlyCollection<{baseColumnType}>";
        }
        else if (isUnknown)
        {
            actualColumnType = $"Unknown<{baseColumnType}>";
        }
        else
        {
            actualColumnType = baseColumnType;
        }

        var columnTypeData = new ColumnTypeData()
        {
            Value = actualColumnType,
            BaseColumnType = baseColumnType,
            IsArray = isArray,
            IsForeignRow = isForeignRow,
            IsUnknown = isUnknown,
            ColumnType = columnType,
        };

        return columnTypeData;
    }

    private static (string columnName, int unknownCounter, bool isUnknown) GetColumnName(Column column, int unknownCounter)
    {
        if (column.Name is not null)
        {
            return (column.Name, unknownCounter, false);
        }

        var name = $"Unknown{unknownCounter}";
        unknownCounter++;

        return (name, unknownCounter, true);
    }

    private void AppendLoadMethod()
    {
        builder.AppendLine($$"""
                public static {{className}}[] Load(Specification specification)
                {
                    if (specification is null)
                    {
                        throw new ArgumentNullException(nameof(specification));
                    }

            """);

        builder.AppendLine("""
                    // loading other required tables


            """);

        builder.AppendLine($$"""
                    var fileToFind = Encoding.ASCII.GetBytes("Data/{{table.Name}}.dat64
                    var fileRecord = specification.DataLoader.GetFileRecord(fileToFind);
                    var decompressedFile = specification.DataLoader.GetFileBytes(fileRecord);

                    var dataOffset = decompressedFile.IndexOfSubArray(Specification.DatFileMagicNumber);
                    const int TableOffset = 4;
                    var offset = 0;
                    (var tableRows, offset) = BitConverterExtended.ToUInt32(decompressedFile, offset);
                    var tableLength = dataOffset - TableOffset;
                    var tableRecordLength = tableLength / (int)tableRows;

                    var objects = new {{className}}[tableRows];
                    for (var rowId = 0; rowId < tableRows; rowId++)
                    {                    
                        // offset = 4 + (rowId * tableRecordLength); // only needed for debug
            """);

        // TODO refactor this shit later.
        for (var i = 0; i < table.Columns.Length; i++)
        {
            var column = table.Columns[i];
            var parsedColumn = parsedColumnTypeData[i];
            var columnName = columnNames[i];

            builder.AppendLine($"""

                                // {columnName.ToLower()}
                    """);

            if (parsedColumn.ColumnType == ColumnTypes.ForeignRow && parsedColumn.IsArray)
            {
                var arrayName = columnName.ToLower();
                var primaryKeys = $"{columnName.ToLower()}PrimaryKeys";
                var referencedTable = TableNameToClassName(column.References.Table);
                builder.AppendLine($$"""
                                (var {{primaryKeys}}, offset) = SpecificationFileLoader.LoadPrimaryKeys(decompressedFile, offset, dataOffset);
                                var {{arrayName}} = new {{referencedTable}}[{{primaryKeys}}.Length];
                                // for (var i = 0; i < {{primaryKeys}}.Length; i++)
                                // {
                                //      var key = {{primaryKeys}}[i];
                                //      var {{referencedTable.ToLower()}}Entry = {{primaryKeys}}[i];
                                //      var {{arrayName}}[i] = {{referencedTable.ToLower()}}Entry;
                                // }
                    """);
            }
            else if (parsedColumn.ColumnType == ColumnTypes.ForeignRow && !parsedColumn.IsArray)
            {
                var primaryKey = $"{columnName.ToLower()}PrimaryKey";
                var referencedTable = TableNameToClassName(column.References.Table);
                builder.AppendLine($$"""
                                (var {{primaryKey}}, offset) = SpecificationFileLoader.LoadPrimaryKey(decompressedFile, offset, dataOffset);
                                {{parsedColumn.Value}} {{referencedTable.ToLower()}}Entry = null;
                                // if ({{primaryKey}} is not null)
                                // {
                                //      {{referencedTable.ToLower()}}Entry = referencedTable[(int){{primaryKey}}];
                                // }
                    """);
            }
            else if (parsedColumn.ColumnType == ColumnTypes.Bool && parsedColumn.IsUnknown)
            {
                builder.AppendLine($"""
                                (var {columnName.ToLower()}, offset) = SpecificationFileLoader.LoadUnknownBoolean(decompressedFile, offset, tableRecordLength);
                    """);
            }
            else if (parsedColumn.ColumnType == ColumnTypes.Bool && !parsedColumn.IsUnknown)
            {
                builder.AppendLine($"""
                                (var {columnName.ToLower()}, offset) = SpecificationFileLoader.LoadBoolean(decompressedFile, offset);
                    """);
            }
            else if (parsedColumn.ColumnType == ColumnTypes.Int && parsedColumn.IsUnknown)
            {
                builder.AppendLine($"""
                                (var {columnName.ToLower()}, offset) = SpecificationFileLoader.LoadUnknownInt(decompressedFile, offset, tableRecordLength);
                    """);
            }
            else if (parsedColumn.ColumnType == ColumnTypes.Int && !parsedColumn.IsUnknown)
            {
                builder.AppendLine($"""
                                (var {columnName.ToLower()}, offset) = SpecificationFileLoader.LoadInt(decompressedFile, offset);
                    """);
            }
            else if (parsedColumn.ColumnType == ColumnTypes.String)
            {
                builder.AppendLine($"""
                                (var {columnName.ToLower()}, offset) = SpecificationFileLoader.LoadString(decompressedFile, offset, dataOffset);
                    """);
            }
            //else if (parsedColumn.ColumnType == ColumnTypes.Row)
            //{

            //}
            //else if (parsedColumn.ColumnType == ColumnTypes.Float)
            //{

            //}
            //else if (parsedColumn.ColumnType == ColumnTypes.None && parsedColumn.IsArray)
            //// else if (parsedColumn.ColumnType == ColumnTypes.Array && parsedColumn.IsArray)
            //{

            //}
            //else if (parsedColumn.ColumnType == ColumnTypes.Enumrow)
            //{

            //}
            else
            {
                var serialized = JsonSerializer.Serialize(parsedColumn, new JsonSerializerOptions()
                {
                    WriteIndented = true,
                    // Encoder = JavaScriptEncoder.Create(UnicodeRanges.All),
                    Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
                });
                var message = $"dont know how to load \n{serialized}";

                // throw new NotImplementedException($"{message}");
                logger.Error(message);
            }

            var strlocal = builder.ToString();
        }

        builder.AppendLine($$"""

                        var obj = new {{className}}()
                        {
            """);

        for (var i = 0; i < table.Columns.Length; i++)
        {
            var column = table.Columns[i];
            var parsedColumn = parsedColumnTypeData[i];
            var columnName = columnNames[i];

            if (parsedColumn.IsArray)
            {
                builder.AppendLine($"""
                                {columnName} = {columnName.ToLower()}.AsReadOnly(),
                """);
            }
            else
            {
                builder.AppendLine($"""
                                {columnName} = {columnName.ToLower()},
                """);
            }
        }


        // obj building ends here
        builder.AppendLine("""
                        };
            """);

        // loop ends here
        builder.AppendLine("""

                    objects[rowId] = obj;
                }
        """);

        // Load() ends here
        builder.AppendLine("""

                    return objects;
                }
            """);
        var str = builder.ToString();
    }
}
