using Serilog;
using System.Diagnostics;
using System.Text;

namespace SpecificationGenerator;

/// <summary>
/// Class containing code for generating Specification.cs file.
/// </summary>
internal class SpecificationFileGenerator
{
    private readonly ILogger logger;
    private readonly List<DatFileGenerator> specificationFiles;

    /// <summary>Gets generated code.</summary>
    public string Code { get; }

    /// <summary>Gets file name.</summary>
    public string FileName { get; } = "Specification.cs";

    /// <summary>
    /// Initializes a new instance of the <see cref="SpecificationFileGenerator"/> class.
    /// </summary>
    /// <param name="logger">logger.</param>
    /// <param name="specificationFiles">specification files.</param>
    public SpecificationFileGenerator(ILogger logger, List<DatFileGenerator> specificationFiles)
    {
        this.logger = logger;
        this.specificationFiles = specificationFiles;
        Code = Generate();
    }

    private string Generate()
    {
        var startTimestamp = Stopwatch.GetTimestamp();
        var builder = new StringBuilder();

        // builder.AppendLine("// <auto-generated />");
        builder.AppendLine($$"""
                // this file is auto generated
                // the generated class is partial, please extend it in another file
                #nullable enable

                using PoeData.Specifications.DatFiles;
                using Serilog;
                using System.Collections.ObjectModel;

                namespace PoeData.Specifications;

                /// <summary>
                /// Class containing all Path of Exile data.
                /// </summary>
                public sealed partial class Specification
                {
                    /// <summary>Gets dat file magic number.</summary>
                    /// thats where the table ends?
                    internal static byte[] DatFileMagicNumber { get; } = new byte[] { (byte)'\xBB', (byte)'\xbb', (byte)'\xBB', (byte)'\xbb', (byte)'\xBB', (byte)'\xbb', (byte)'\xBB', (byte)'\xbb' };

                    private readonly DataLoader dataLoader;

                    /// <summary>
                    /// Initializes a new instance of the <see cref="Specification"/> class.
                    /// </summary>
                    /// <param name="config">Contains config data.</param>
                    /// <param name="logger">Contains logger used through the application.</param>
                    public Specification(IConfig config, ILogger logger)
                    {
                        if (config is null)
                        {
                            throw new ArgumentNullException(nameof(config));
                        }

                        if (logger is null)
                        {
                            throw new ArgumentNullException(nameof(logger));
                        }

                        dataLoader = new DataLoader(config, logger);
                    }
                """);

        AppendLoadMethods(builder);

        builder.AppendLine("""
            }
            """);

        var str = builder.ToString();

        logger.Verbose("generated {fileName} string in {elapsed}", FileName, Stopwatch.GetElapsedTime(startTimestamp));
        return str;
    }

    private void AppendLoadMethods(StringBuilder builder)
    {
        foreach (var file in specificationFiles)
        {
            var className = file.ClassName;
            builder.AppendLine($$"""

                    /// <summary>
                    /// Gets {{className}} data.
                    /// </summary>
                    /// <returns>readonly collection of {{className}}.</returns>
                    public ReadOnlyCollection<{{className}}> Load{{className}}()
                    {
                        return {{className}}.Load(dataLoader).AsReadOnly();
                    }
                """);
        }
    }
}
