using Serilog;
using System.Diagnostics;
using System.Text;

namespace SpecificationGenerator;

/// <summary>
/// Class containing code for generating Specification.cs file.
/// </summary>
internal class SpecificationFileGenerator
{
    private readonly ILogger logger;
    private readonly IReadOnlyList<RepositoryGenerator> repositoryFiles;

    /// <summary>Gets generated code.</summary>
    public string Code { get; }

    /// <summary>Gets file name.</summary>
    public string FileName { get; } = "Specification.cs";

    /// <summary>
    /// Initializes a new instance of the <see cref="SpecificationFileGenerator"/> class.
    /// </summary>
    /// <param name="logger">logger.</param>
    /// <param name="repositoryFiles">repository files.</param>
    public SpecificationFileGenerator(ILogger logger, IReadOnlyList<RepositoryGenerator> repositoryFiles)
    {
        this.logger = logger;
        this.repositoryFiles = repositoryFiles;
        Code = Generate();
    }

    private string Generate()
    {
        var startTimestamp = Stopwatch.GetTimestamp();
        var builder = new StringBuilder();

        // builder.AppendLine("// <auto-generated />");
        builder.AppendLine($$"""
            // this file is auto generated
            // the generated class is partial, please extend it in another file
            #nullable enable
            
            using PoeData.Specifications.Repositories;
            using Serilog;
            
            namespace PoeData.Specifications;
            
            /// <summary>
            /// Class containing all Path of Exile data.
            /// </summary>
            public sealed partial class Specification
            {
                /// <summary>Gets dat file magic number.</summary>
                /// thats where the table ends?
                internal static byte[] DatFileMagicNumber { get; } = new byte[] { (byte)'\xBB', (byte)'\xbb', (byte)'\xBB', (byte)'\xbb', (byte)'\xBB', (byte)'\xbb', (byte)'\xBB', (byte)'\xbb' };
            
                private readonly DataLoader dataLoader;
                private readonly ILogger logger;
            
                /// <summary>Gets data loader.</summary>
                internal DataLoader DataLoader => dataLoader;
            
            """);

        AppendFields(builder);

        builder.AppendLine($$"""

                    /// <summary>
                    /// Initializes a new instance of the <see cref="Specification"/> class.
                    /// </summary>
                    /// <param name="config">Contains config data.</param>
                    /// <param name="logger">Contains logger used through the application.</param>
                    public Specification(IConfig config, ILogger logger)
                    {
                        if (config is null)
                        {
                            throw new ArgumentNullException(nameof(config));
                        }

                        if (logger is null)
                        {
                            throw new ArgumentNullException(nameof(logger));
                        }

                        dataLoader = new DataLoader(config, logger);
                        
                        this.logger = logger;
                    }
                """);

        AppendLoadMethods(builder);

        builder.AppendLine("""
            }
            """);

        var str = builder.ToString();

        logger.Verbose("generated {fileName} string in {elapsed}", FileName, Stopwatch.GetElapsedTime(startTimestamp));
        return str;
    }

    private void AppendFields(StringBuilder builder)
    {
        foreach (var file in repositoryFiles)
        {
            var className = file.ClassName;
            var fieldName = GenerateFieldName(file);
            builder.AppendLine($"""
                    private {className}? {fieldName};
                """);
        }
    }

    private void AppendLoadMethods(StringBuilder builder)
    {
        foreach (var file in repositoryFiles)
        {
            var className = file.ClassName;
            var fieldName = GenerateFieldName(file);
            builder.AppendLine($$"""

                    /// <summary>
                    /// Gets {{className}} data.
                    /// </summary>
                    /// <returns>repository of {{className}}.</returns>
                    public {{className}} Load{{className}}()
                    {
                        {{fieldName}} ??= new {{className}}(logger, this);
                        return {{fieldName}};
                    }
                """);
        }
    }

    private static string GenerateFieldName(RepositoryGenerator repository)
    {
        return repository.ClassName.ToLower();
    }
}
