using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

namespace PoeExporterGenerator.LuaGenerator;

/// <summary>
/// Class used to generate to LuaString generate methods.
/// </summary>
[Generator]
internal class LuaStringGenerator : ISourceGenerator
{
    private const string LuaStringClassName = "LuaString";

    /// <inheritdoc/>
    public void Execute(GeneratorExecutionContext context)
    {
        var classes = LuaStringHelpers.GetClassDeclarations(context);

        var builder = new StringBuilder();

        builder.AppendLine($$"""
            // <auto-generated/>
                        
            using System.Text;

            namespace PoeExporter.WikiExporters.Lua.Helpers;
                        
            internal readonly partial record struct {{LuaStringClassName}}
            {
            """);

        foreach (var classDeclaration in classes)
        {
            AddGenerateMethod(classDeclaration, builder);
        }

        builder.AppendLine("""
            }
            """);

        var str = builder.ToString();

        context.AddSource($"{LuaStringClassName}.g.cs", str);
    }

    /// <inheritdoc/>
    public void Initialize(GeneratorInitializationContext context)
    {
    }

    private void AddGenerateMethod(ClassDeclarationSyntax classDeclaration, StringBuilder builder)
    {
        var className = classDeclaration.Identifier.ValueText;
        builder.AppendLine($$"""

                /// <summary>
                /// Generates lua strings for another <see cref="ILuaExporter{T}"/>.
                /// </summary>
                /// <param name="name">name of a lua variable.</param>
                /// <param name="exporter">exporter to generater values from.</param>
                /// <param name="indentation">indentation of lua strings.</param>
                /// <returns>parsed lua strings.</returns>
                internal static LuaString[] Generate(string name, {{className}} exporter, int indentation)
                {
                    var strings = LuaConverter.ToLuaStrings(exporter, indentation);
                    var first = strings[0];
                    var overridenFirst = new LuaString($"{name} = {first.Value}", indentation);
                    strings[0] = overridenFirst;

                    return strings;
                }
            """);
    }
}
